
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: rol; Type: TYPE; Schema: public; Owner: omega
--

CREATE TYPE public.rol AS ENUM (
    'ROLE_ADMIN',
    'ROLE_EMPLEADO'
);


ALTER TYPE public.rol OWNER TO omega;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categorias; Type: TABLE; Schema: public; Owner: omega
--

CREATE TABLE public.categorias (
                                   id BIGINT NOT NULL,
                                   nombre character varying(100) NOT NULL,
                                   ultimo_sku BIGINT DEFAULT 0
);


ALTER TABLE public.categorias OWNER TO omega;

--
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: omega
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: omega
--

CREATE TABLE public.productos (
                                  id BIGINT NOT NULL,
                                  disponible boolean,
                                  marca character varying(100),
                                  nombre character varying(150) NOT NULL,
                                  id_categoria BIGINT
);


ALTER TABLE public.productos OWNER TO omega;

--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: omega
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: omega
--

CREATE TABLE public.usuarios (
                                 id BIGINT NOT NULL,
                                 email character varying(255) NOT NULL,
                                 nombre character varying(200),
                                 password character varying(255) NOT NULL,
                                 creado_el timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 actualizado_el timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 rol public.rol NOT NULL
);


ALTER TABLE public.usuarios OWNER TO omega;

--
-- Name: variantes; Type: TABLE; Schema: public; Owner: omega
--

CREATE TABLE public.variantes (
                                  id BIGINT NOT NULL,
                                  color character varying(50) NOT NULL,
                                  precio numeric(38,2) NOT NULL,
                                  sku character varying(255),
                                  stock integer NOT NULL,
                                  talla character varying(50) NOT NULL,
                                  producto_id BIGINT
);


ALTER TABLE public.variantes OWNER TO omega;

--
-- Name: variantes_id_seq; Type: SEQUENCE; Schema: public; Owner: omega
--

ALTER TABLE public.variantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.variantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias categoria_nombre_unico; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categoria_nombre_unico UNIQUE (nombre);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: variantes uktpv26x89gfjtlh97kj4djyn0b; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.variantes
    ADD CONSTRAINT uktpv26x89gfjtlh97kj4djyn0b UNIQUE (sku);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: variantes variantes_pkey; Type: CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.variantes
    ADD CONSTRAINT variantes_pkey PRIMARY KEY (id);


--
-- Name: productos fkdtoa37luoxhhvbicrfiu5ygbj; Type: FK CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fkdtoa37luoxhhvbicrfiu5ygbj FOREIGN KEY (id_categoria) REFERENCES public.categorias(id);


--
-- Name: variantes fkqy7ffq0bdlclwb5vgpwn20m02; Type: FK CONSTRAINT; Schema: public; Owner: omega
--

ALTER TABLE ONLY public.variantes
    ADD CONSTRAINT fkqy7ffq0bdlclwb5vgpwn20m02 FOREIGN KEY (producto_id) REFERENCES public.productos(id);


